export const airportsMockData =  ['ATL - Atlanta GA, US', 'PEK - Beijing, CN', 'LHR - London, GB', 'ORD - Chicago IL, US', 'HND - Tokyo, JP',
  'LAX - Los Angeles CA, US', 'CDG - Paris, FR', 'DFW - Dallas/fort Worth TX, US', 'FRA - Frankfurt, DE',
  'HKG - Hong Kong, HK', 'DEN - Denver CO, US', 'DXB - Dubai, AE', 'CGK - Jakarta, ID', 'AMS - Amsterdam, NL', 'MAD - Madrid, ES',
  'BKK - Bangkok, TH', 'JFK - New York NY, US', 'SIN - Singapore, SG', 'CAN - Guangzhou, CN', 'LAS - Las Vegas NV, US',
  'PVG - Shanghai, CN', 'SFO - San Francisco CA, US', 'PHX - Phoenix AZ, US', 'IAH - Houston TX, US', 'CLT - Charlotte NC, US',
  'MIA - Miami FL, US', 'MUC - Munich, DE', 'KUL - Kuala Lumpur, MY', 'FCO - Rome, IT', 'IST - Istanbul, TR', 'SYD - Sydney, AU',
  'MCO - Orlando FL, US', 'ICN - Incheon, KR', 'DEL - New Delhi, IN', 'BCN - Barcelona, ES', 'LGW - London, GB', 'EWR - Newark NJ, US',
  'YYZ - Toronto ON, CA', 'SHA - Shanghai, CN', 'MSP - Minneapolis MN, US', 'SEA - Seattle WA, US', 'DTW - Detroit MI, US',
  'PHL - Philadelphia PA, US', 'BOM - Mumbai, IN', 'GRU - São Paulo, BR', 'MNL - Manila, PH', 'CTU - Chengdu, CN',
  'BOS - Boston MA, US', 'SZX - Shenzhen, CN', 'MEL - Melbourne, AU', 'NRT - Tokyo, JP', 'ORY - Paris, FR', 'MEX - Mexico City, MX',
  'DME - Moscow, RU', 'AYT - Antalya, TR', 'TPE - Taipei, TW', 'ZRH - Zurich, CH', 'LGA - New York NY, US', 'FLL - Fort Lauderdale FL, US',
  'IAD - Washington, DC, US', 'PMI - Palma De Mallorca, ES', 'CPH - Copenhagen, DK', 'SVO - Moscow, RU', 'BWI - Baltimore MD, US',
  'KMG - Kunming, CN', 'VIE - Vienna, AT', 'OSL - Oslo, NO', 'JED - Jeddah, SA', 'BNE - Brisbane, AU', 'SLC - Salt Lake City UT, US',
  'DUS - Düsseldorf, DE', 'BOG - Bogota, CO', 'MXP - Milan, IT', 'JNB - Johannesburg, ZA', 'ARN - Stockholm, SE', 'MAN - Manchester, GB',
  'MDW - Chicago IL, US', 'DCA - Washington DC, US', 'BRU - Brussels, BE', 'DUB - Dublin, IE', 'GMP - Seoul, KR', 'DOH - Doha, QA',
  'STN - London, GB', 'HGH - Hangzhou, CN', 'CJU - Jeju, KR', 'YVR - Vancouver BC, CA', 'TXL - Berlin, DE', 'SAN - San Diego CA, US',
  'TPA - Tampa FL, US', 'CGH - São Paulo, BR', 'BSB - Brasilia, BR', 'CTS - Sapporo, JP', 'XMN - Xiamen, CN', 'RUH - Riyadh, SA',
  'FUK - Fukuoka, JP', 'GIG -  Rio De Janeiro, BR', 'HEL - Helsinki, FI', 'LIS - Lisbon, PT', 'ATH - Athens, GR', 'AKL - Auckland, NZ'];
