// Please do not edit this file to change the proxy to your personal needs.
// Instead copy this file to `proxy.js` and modify this file. It will
// not be submitted to source control.
//
// For details see https://rndwww.nce.amadeus.net/confluence/display/SECODOC/Proxy+for+SECO+backend+or+mock+your+server+response

module.exports = {
  "/app_sell2.0": {
    "target": "https://ncebpm0720aph01.etv.nce.amadeus.net",
    "secure": false,
    "logLevel": "debug"
  },
  "/aria": {
    "target": "https://ncebpm0720aph01.etv.nce.amadeus.net",
    "secure": false,
    "logLevel": "debug"
  },
  "/LoginService": {
    "target": "https://pdt.accounts.sellingplatformconnect.amadeus.com",
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  }
};
